name: Terraform Dev Destroy with OIDC

on:
  workflow_dispatch:  # Manual trigger via GitHub UI

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/914342142012/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-oidc-sa@devops-project-458912.iam.gserviceaccount.com"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: envs/stg

      - name: Terraform Destroy
        run: terraform destroy -var-file="stg.tfvars" -auto-approve
        working-directory: envs/stg
